# Generated by Django 4.1.6 on 2023-02-09 08:34

from django.db import migrations, models
import django.db.models.deletion
import parler.fields
import parler.models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ElectionCandidate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name="ElectionParty",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name="ElectionPartyTranslation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "language_code",
                    models.CharField(
                        db_index=True, max_length=15, verbose_name="Language"
                    ),
                ),
                ("Name", models.CharField(max_length=90)),
                ("Description", models.CharField(max_length=250)),
                (
                    "master",
                    parler.fields.TranslationsForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="translations",
                        to="vaalikone_app.electionparty",
                    ),
                ),
            ],
            options={
                "verbose_name": "election party Translation",
                "db_table": "vaalikone_app_electionparty_translation",
                "db_tablespace": "",
                "managed": True,
                "default_permissions": (),
                "unique_together": {("language_code", "master")},
            },
            bases = (parler.models.TranslatableModel, models.Model)
        ),
        migrations.CreateModel(
            name="ElectionCandidateTranslation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "language_code",
                    models.CharField(
                        db_index=True, max_length=15, verbose_name="Language"
                    ),
                ),
                ("FirstName", models.CharField(max_length=30)),
                ("LastName", models.CharField(max_length=30)),
                ("CandidateNumber", models.IntegerField(max_length=50)),
                (
                    "Party",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="vaalikone_app.electionparty",
                    ),
                ),
                (
                    "master",
                    parler.fields.TranslationsForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="translations",
                        to="vaalikone_app.electioncandidate",
                    ),
                ),
            ],
            options={
                "verbose_name": "election candidate Translation",
                "db_table": "vaalikone_app_electioncandidate_translation",
                "db_tablespace": "",
                "managed": True,
                "default_permissions": (),
                "unique_together": {("language_code", "master")},
            },
            bases = (parler.models.TranslatableModel, models.Model)
        ),
    ]
